/**
 * The compiled guest module, as bytes.
 *
 * `kernel.wasm` is committed next to `kernel.wat`, but a browser tab has no
 * filesystem to read it from, so the bytes also travel as base64 in the generated
 * `kernel-bytes.ts`. `atob` is a global in Node and in every browser, so decoding
 * needs no platform branch and no dependency.
 *
 * The two representations are generated by one script and asserted equal — along
 * with a fresh recompilation of the `.wat` — in `kernel-build.node.test.ts`.
 */

import { KERNEL_WASM_BASE64 } from './kernel-bytes.ts'

function decodeBase64(text: string): Uint8Array<ArrayBuffer> {
  const binary = atob(text)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

/** The admitted module, ready to `blockstore.put()`. */
export const kernelBytes: Uint8Array<ArrayBuffer> = decodeBase64(KERNEL_WASM_BASE64)
