/**
 * GENERATED — do not edit. Run `npm run build:kernel --workspace @o2/demo` to regenerate.
 *
 * The bytes of `kernel.wasm`, base64-encoded, because the portable test suite and the
 * browser demo both run where there is no filesystem. `kernel-build.node.test.ts`
 * asserts these bytes equal both the committed `kernel.wasm` and a fresh recompilation
 * of `kernel.wat`.
 */

export const KERNEL_WASM_BASE64: string =
  'AGFzbQEAAAABGAVgAAF/YAJ/fwF/YAJ/fwBgAX8Bf2AAAAJBBAJvMglpbnB1dF9sZW4AAAJvMgppbnB1dF9yZWFkAAECbzIM' +
  'b3V0cHV0X3dyaXRlAAICbzIJcGFydGl0aW9uAAADBAMDAwQFBAEBBAQGSAx/AEEAC38AQYAgC38AQYCAAQt/AEGAgAILfwBB' +
  'gMAAC38AQaCcAQt/AEGAgA4LfwBBAgt/AUEAC38BQQALfwFBAAt/AUEACwcQAgZtZW1vcnkCAANydW4ABgrgBwOiAQEHfyMK' +
  'IABBAnRqKAAAIQEjCiAAQQJ0aigABCECAkADQCABIAJPDQEjCCMLIAFBAXRqLwAAQQZsaiEDIAMvAAAhBCADLwACIQUgAy8A' +
  'BCEGIwIgBGotAAAjAiAFai0AACMCIAZqLQAAcXEEQCMBIARqLQAAIQcgByMBIAVqLQAARiAHIwEgBmotAABGcQRAQQAPCwsg' +
  'AUEBaiEBDAALC0EBCw0AIwkgAEEBdGovAAALqwYBEn9BAiEQAkAQACEAIAAjBksNACMDIAAQARpBASEBIwMtAAAhDiAOQdgA' +
  'RgRAQQIhAQsgDkHZAEYEQEEDIQELIA5B2gBGBEBBBSEBCyAAIAFBDGpJDQAjAyABaiECIAIoAAAhBCACKAAEIQUgAigACCEG' +
  'IAQjBEsNACAGIwVLDQAgAkEMaiQIIwggBkEGbGohAyADQQRqJAkjCSAEQQF0aiQKIwogBEECakECdGokCyMLIAZBBmxqIwMg' +
  'AGpLDQAgAygAACMHRw0AQQAhDgJAA0AgDiAESw0BIwIgDmpBADoAACAOQQFqIQ4MAAsLEAMhByAHQRB2IQggB0H//wNxIQkg' +
  'CUUEQEEBIQkLQR8gCWdrIQogCiAESgRAIAQhCgtBACELAkADQCALIApODQEgCxAFIQwjASAMaiAIIAt2QQFxOgAAIwIgDGpB' +
  'AToAACALQQFqIQsMAAsLQQAhCwJAA0AgCyAKTg0BIAsQBRAERQRAQQAhEAwDCyALQQFqIQsMAAsLQQAhDyAKIQsgCyAESARA' +
  'IAsQBSEMIwEgDGpBADoAACMCIAxqQQE6AAALAkADQCALIAROBEBBASEQDAILIAsQBSEMIAwQBARAIAtBAWohCyALIARIBEAg' +
  'CxAFIQ0jASANakEAOgAAIwIgDWpBAToAAAsMAQsCQANAIwEgDGotAABFBEAjASAMakEBOgAADAILIwIgDGpBADoAACALQQFr' +
  'IQsgD0EBaiEPIAsgCkgEQEEAIRAMBAsgDyAFTwRAQQIhEAwECyALEAUhDAwACwsMAAsLCyMAQaIBOgAAIwBB4QA6AAEjAEHj' +
  'ADoAAiMAQdkAOgADIwBBBDoABCMAQQA6AAUjAEHhADoAhggjAEHzADoAhwgjAEHBADoAiAgjACAQOgCJCEEAIQ4CQANAIA5B' +
  'gAJPDQEjACAOQQJ0akEANgAGIA5BAWohDgwACwsgEEEBRgRAQQEhDAJAA0AgDCAESw0BIwEgDGotAAAEQCMAQQZqIAxBAWtB' +
  'A3ZqIREgESARLQAAQQEgDEEBa0EHcXRyOgAACyAMQQFqIQwMAAsLCyMAQYoIEAIL'
