/**
 * GENERATED — do not edit. Run `npm run build:primes --workspace @o2/demo` to regenerate.
 *
 * The bytes of `primes.wasm`, base64-encoded, because the portable test suite and the
 * browser both run where there is no filesystem. `primes-build.node.test.ts` asserts
 * these bytes equal both the committed `primes.wasm` and a fresh recompilation of
 * `primes.wat`.
 */

export const PRIMES_WASM_BASE64: string =
  'AGFzbQEAAAABIwdgAAF/YAJ/fwF/YAJ/fwBgAX8Bf2ABfwBgA39/fwF+YAAAAkEEAm8yCWlucHV0X2xlbgAAAm8yCmlucHV0' +
  'X3JlYWQAAQJvMgxvdXRwdXRfd3JpdGUAAgJvMglwYXJ0aXRpb24AAAMKCQMEAwQBAwMFBgUEAQEEBAZJC38AQQALfwBBgAIL' +
  'fwBBgCALfwBBgIABC38AQYCAAwt/AEGAHgt/AEGAwAALfwBBgMAAC38AQYCAEAt/AEH/////Bwt/AEEBCwcQAgZtZW1vcnkC' +
  'AANydW4ADArBBwkWACMCIABBA3ZqLQAAIABBB3F2QQFxCyEBAX8jAiAAQQN2aiEBIAEgAS0AAEEBIABBB3F0cjoAAAsWACME' +
  'IABBA3ZqLQAAIABBB3F2QQFxCyEBAX8jBCAAQQN2aiEBIAEgAS0AAEEBIABBB3F0cjoAAAsMACAAIAEgACABSRsLKQEBf0EA' +
  'IQECQANAIAFBAWogAUEBamwgAEsNASABQQFqIQEMAAsLIAELtgEBA39BACEBAkADQCABQYAQTw0BIwIgAUECdGpBADYCACAB' +
  'QQFqIQEMAAsLQQIhAQJAA0AgASABbCAASw0BIAEQBEUEQCABIAFsIQICQANAIAIgAEsNASACEAUgAiABaiECDAALCwsgAUEB' +
  'aiEBDAALC0EAIQNBAiEBAkADQCABIABLDQEgARAERQRAIAMjBkkEQCMDIANBAnRqIAE2AAAgA0EBaiEDCwsgAUEBaiEBDAAL' +
  'CyADC4gCAgF+CH9CACEDIAAhBAJAA0AgBCABTw0BIAQjCGohBSAFIAFLBEAgASEFCyAFIARrIQYgBkEfakEFdiEHQQAhCAJA' +
  'A0AgCCAHTw0BIwQgCEECdGpBADYCACAIQQFqIQgMAAsLQQAhCAJAA0AgCCACTw0BIwMgCEECdGooAAAhCSAJIAlsIAVPDQEg' +
  'CSAJbCEKIAogBEkEQCAEIAlqQQFrIAluIAlsIQoLIAohCwJAA0AgCyAFTw0BIAsgBGsQByALIAlqIQsMAAsLIAhBAWohCAwA' +
  'CwtBACELAkADQCALIAZPDQEgCxAGRQRAIANCAXwhAwsgC0EBaiELDAALCyAFIQQMAAsLIAML0wICEH8BfkEBIQ9CACEQAkAQ' +
  'ACEAIAAjBUsNACMBIAAQARpBASEBIwEtAAAhAyADQdgARgRAQQIhAQsgA0HZAEYEQEEDIQELIANB2gBGBEBBBSEBCyAAIAFB' +
  'CGpJDQAjASABaiECIAIoAAAjCkcNACACKAAEIQQgBCMJSw0AEAMhByAHQRB2IQggB0H//wNxIQkgCUUEQEEBIQkLIAggCU8N' +
  'AEEAIQogBEECTwRAIARBAWshCgsgCiAJbiELIAogCXAhDEECIAggC2wgCCAMEAhqaiENIAhBAWohA0ECIAMgC2wgAyAMEAhq' +
  'aiEOIAQQCSEFIAUQCiEGIA0gDiAGEAshEEEAIQ8LIwBBogE6AAAjAEHhADoAASMAQeMAOgACIwBByAA6AAMjACAQNwAEIwBB' +
  '4QA6AAwjAEHzADoADSMAQcEAOgAOIwAgDzoADyMAQRAQAgs='
