/**
 * The compiled WASI fixtures, as bytes, in a form a browser can reach.
 *
 * Each `.wasm` is committed next to the `.wat` it came from, but the portable test
 * suite also runs in real Chromium, where there is no filesystem to read it from —
 * so the bytes travel as base64 in the generated `wasi-fixture-bytes.ts` as well.
 * `atob` is a global in Node and in every browser, so decoding needs no platform
 * branch and no dependency.
 *
 * All three representations — `.wat`, `.wasm`, base64 — are generated by one script
 * and asserted equal in `wasi-fixtures.node.test.ts`. A committed binary that nothing
 * checks is an unverifiable claim about the source sitting next to it, and these
 * binaries are the only evidence that `WasiExecutor` has ever run a WASI module at
 * all.
 *
 * The map is keyed by the same names `scripts/compile-wasi-fixture.mjs` lists, so the
 * build test can walk the directory and require the three lists to agree rather than
 * trusting that whoever added a fixture also remembered to register it.
 */

import {
  WASI_ECHO_BASE64,
  WASI_ENV_BASE64,
  WASI_FAIL_BASE64,
  WASI_FDSTAT_BASE64,
  WASI_HOSTCALL_BASE64,
  WASI_NO_MEMORY_BASE64,
  WASI_NO_START_BASE64,
  WASI_NOISY_BASE64,
  WASI_PROBE_BASE64,
  WASI_SHARD_BASE64,
  WASI_THREAD_SPAWN_BASE64,
} from './wasi-fixture-bytes.ts'

function decodeBase64(text: string): Uint8Array<ArrayBuffer> {
  const binary = atob(text)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i)
  return bytes
}

/** Reads stdin to EOF, writes it back to stdout, exits 0. */
export const wasiEcho: Uint8Array<ArrayBuffer> = decodeBase64(WASI_ECHO_BASE64)

/** Emits the raw argv byte buffer as a DAG-CBOR byte string. */
export const wasiShard: Uint8Array<ArrayBuffer> = decodeBase64(WASI_SHARD_BASE64)

/** Emits 48 bytes: two clock reads each of two clocks, then two entropy draws. */
export const wasiProbe: Uint8Array<ArrayBuffer> = decodeBase64(WASI_PROBE_BASE64)

/** Writes valid DAG-CBOR to stdout and then exits 7. */
export const wasiFail: Uint8Array<ArrayBuffer> = decodeBase64(WASI_FAIL_BASE64)

/** Emits the fdstat of stdin and stdout, and the filestat of stdin. */
export const wasiFdstat: Uint8Array<ArrayBuffer> = decodeBase64(WASI_FDSTAT_BASE64)

/** Emits the environment as `environ_sizes_get`/`environ_get` presented it. */
export const wasiEnv: Uint8Array<ArrayBuffer> = decodeBase64(WASI_ENV_BASE64)

/** Emits the errno and the out-parameter bytes of every behaviourally pinned call. */
export const wasiHostcall: Uint8Array<ArrayBuffer> = decodeBase64(WASI_HOSTCALL_BASE64)

/** Writes 4800 bytes to stderr, then traps on input `1` and exits 9 on anything else. */
export const wasiNoisy: Uint8Array<ArrayBuffer> = decodeBase64(WASI_NOISY_BASE64)

/** Exports `memory` only — not a command module. */
export const wasiNoStart: Uint8Array<ArrayBuffer> = decodeBase64(WASI_NO_START_BASE64)

/** Exports `_start` only — no linear memory for the host to write into. */
export const wasiNoMemory: Uint8Array<ArrayBuffer> = decodeBase64(WASI_NO_MEMORY_BASE64)

/** Imports `wasi_snapshot_preview1.thread_spawn`, which the host does not supply. */
export const wasiThreadSpawn: Uint8Array<ArrayBuffer> = decodeBase64(WASI_THREAD_SPAWN_BASE64)

/** Every fixture, keyed by the name its `.wat` and `.wasm` files carry. */
export const WASI_FIXTURES: Readonly<Record<string, Uint8Array<ArrayBuffer>>> = {
  'wasi-echo': wasiEcho,
  'wasi-shard': wasiShard,
  'wasi-probe': wasiProbe,
  'wasi-fail': wasiFail,
  'wasi-fdstat': wasiFdstat,
  'wasi-env': wasiEnv,
  'wasi-hostcall': wasiHostcall,
  'wasi-noisy': wasiNoisy,
  'wasi-no-start': wasiNoStart,
  'wasi-no-memory': wasiNoMemory,
  'wasi-thread-spawn': wasiThreadSpawn,
}
